// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: telemetry.proto

package logagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogCollector_SendLogs_FullMethodName = "/logagent.LogCollector/SendLogs"
)

// LogCollectorClient is the client API for LogCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogCollectorClient interface {
	SendLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, Ack], error)
}

type logCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogCollectorClient(cc grpc.ClientConnInterface) LogCollectorClient {
	return &logCollectorClient{cc}
}

func (c *logCollectorClient) SendLogs(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[LogEntry, Ack], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogCollector_ServiceDesc.Streams[0], LogCollector_SendLogs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogEntry, Ack]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogCollector_SendLogsClient = grpc.ClientStreamingClient[LogEntry, Ack]

// LogCollectorServer is the server API for LogCollector service.
// All implementations must embed UnimplementedLogCollectorServer
// for forward compatibility.
type LogCollectorServer interface {
	SendLogs(grpc.ClientStreamingServer[LogEntry, Ack]) error
	mustEmbedUnimplementedLogCollectorServer()
}

// UnimplementedLogCollectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogCollectorServer struct{}

func (UnimplementedLogCollectorServer) SendLogs(grpc.ClientStreamingServer[LogEntry, Ack]) error {
	return status.Errorf(codes.Unimplemented, "method SendLogs not implemented")
}
func (UnimplementedLogCollectorServer) mustEmbedUnimplementedLogCollectorServer() {}
func (UnimplementedLogCollectorServer) testEmbeddedByValue()                      {}

// UnsafeLogCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogCollectorServer will
// result in compilation errors.
type UnsafeLogCollectorServer interface {
	mustEmbedUnimplementedLogCollectorServer()
}

func RegisterLogCollectorServer(s grpc.ServiceRegistrar, srv LogCollectorServer) {
	// If the following call pancis, it indicates UnimplementedLogCollectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogCollector_ServiceDesc, srv)
}

func _LogCollector_SendLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogCollectorServer).SendLogs(&grpc.GenericServerStream[LogEntry, Ack]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogCollector_SendLogsServer = grpc.ClientStreamingServer[LogEntry, Ack]

// LogCollector_ServiceDesc is the grpc.ServiceDesc for LogCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "logagent.LogCollector",
	HandlerType: (*LogCollectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendLogs",
			Handler:       _LogCollector_SendLogs_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "telemetry.proto",
}
