env: "dev"

storage:
  type: "clickhouse"
  address: "clickhouse_container:9000"
  database: "telemetry_db"
  table: "telemetry_data"
  username: "telemetry_user"
  password: "telemetry_pass"
  batch_size: 1000
  flush_timeout: 1s
  migration_path: "/app/migrate/00001_create_telemetry_table.sql"

grpc_server:
  grpc_port: 9001
  max_msg_size_mb: 10
