name: collector service CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: self-hosted 
  
    steps:
      - name: Checkout code 
        uses: actions/checkout@4

      - name: Set up Docker buildx 
        uses: docker/setup-buildx-action@v2
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
        
      - name: Build and start services
        run: docker compose up -d --build
      
      - name: Run e2e test 
        run: |
          go test ./collector-service/test/... -v
      
      - name: Stop and remove services 
        if: always()
        run: docker compose down -v
     