name: collector service CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: self-hosted 
  
    steps:
      - name: Checkout code 
        uses: actions/checkout@v3

      - name: Set up Docker buildx 
        uses: docker/setup-buildx-action@v2
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.4
      - name: Create .env file
        run: echo "CONFIG_PATH=${{ secrets.CONFIG_PATH }}" >> ./dashboard/.env
        
      - name: Build and start services
        run: docker compose up -d --build
      
      - name: Configure go mod
        run: cd collector-service && go mod tidy

      - name: Run e2e test 
        run: |
          cd collector-service && go test ./tests/... -v
      
      - name: Deploy service  
        run: |
          docker compose down -v
          docker compose up -d 
     